version: '3.1'

services:
  cipher:
    container_name: cipher
    build:
      context: .
      dockerfile: ./Dockerfile
    environment:
      SECRET_KEY: ${SECRET_KEY}
      ALGORITHM: ${ALGORITHM}
      DEFAULT_USER: ${DEFAULT_USER}
      DEFAULT_PASSWORD: ${DEFAULT_PASSWORD}
      DATABASE_URL: ${DATABASE_URL}
    ports:
      - 80:80